services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kiennt26/clicklens:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.env.local:/app/.env.local
    environment:
      - NODE_ENV=production
      - DISABLE_SECURE_COOKIES=true
    restart: unless-stopped
